version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:43"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
